version: '2'
services:
  qnow1-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/Qnow1/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Qnow1
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
